# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eebc045bf4b03531b440dad75b0e11107ddfa7287085c968e191506c1229eb6eb516850484c0d9ea8b60c69e46be2fb2fc5764270599998dfc414c5e434fec1

test:
  secret_key_base: fad7c53ec0099d68c04c008df39f830f670488a0e80b66a2a5242000cca5d930b85c00fa6a82854b9160c174548a66aa9b50d29b6ae79f620c322b8f6e4851c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
